# Generated by Django 5.2.17 on 2026-10-01 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TwoFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secret", models.CharField(max_length=64, verbose_name="Секрет")),
                (
                    "confirmed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Включён"),
                ),
                (
                    "last_step",
                    models.BigIntegerField(
                        default=0, verbose_name="Последний принятый шаг"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "двухфакторный вход",
                "verbose_name_plural": "Двухфакторный вход",
            },
        ),
    ]
