# Generated by Django 5.2.17 on 2026-10-01 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hse_id",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Код на hse.ru"
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Название")),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок в направлении"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Показывать на сайте"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("hse", "Сайт НИУ ВШЭ"), ("manual", "Вручную")],
                        default="manual",
                        max_length=10,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "locked",
                    models.BooleanField(
                        default=False,
                        help_text="Ручные правки сохранятся при обновлении каталога",
                        verbose_name="Не обновлять с hse.ru",
                    ),
                ),
                (
                    "hse_url",
                    models.URLField(blank=True, verbose_name="Страница на hse.ru"),
                ),
                (
                    "type_short",
                    models.CharField(
                        help_text="ПК или ПП",
                        max_length=20,
                        verbose_name="Тип (кратко)",
                    ),
                ),
                ("type_title", models.CharField(max_length=100, verbose_name="Тип")),
                (
                    "study_format",
                    models.CharField(max_length=200, verbose_name="Формат"),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Длительность"
                    ),
                ),
                (
                    "hours",
                    models.CharField(blank=True, max_length=100, verbose_name="Объём"),
                ),
                (
                    "language",
                    models.CharField(blank=True, max_length=100, verbose_name="Язык"),
                ),
                (
                    "schedule",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="График занятий"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Старт"),
                ),
                (
                    "start_month_only",
                    models.BooleanField(
                        default=False, verbose_name="Известен только месяц старта"
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Цена со скидкой, ₽"
                    ),
                ),
                (
                    "base_price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Цена, ₽"
                    ),
                ),
                (
                    "tax_refund",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Налоговый вычет"
                    ),
                ),
                (
                    "tagline",
                    models.TextField(blank=True, verbose_name="Короткое описание"),
                ),
                ("about", models.TextField(blank=True, verbose_name="О программе")),
                (
                    "audience_intro",
                    models.TextField(
                        blank=True, verbose_name="Кому подойдёт: вступление"
                    ),
                ),
                (
                    "audience",
                    models.TextField(
                        blank=True,
                        help_text="По одному пункту на строку",
                        verbose_name="Кому подойдёт",
                    ),
                ),
                (
                    "results",
                    models.TextField(
                        blank=True,
                        help_text="По одному пункту на строку",
                        verbose_name="Чему научитесь",
                    ),
                ),
                (
                    "advantages",
                    models.TextField(
                        blank=True,
                        help_text="По одному пункту на строку",
                        verbose_name="Преимущества",
                    ),
                ),
                (
                    "discounts",
                    models.TextField(
                        blank=True,
                        help_text="По одному пункту на строку",
                        verbose_name="Скидки",
                    ),
                ),
                (
                    "admission_documents",
                    models.TextField(
                        blank=True,
                        help_text="По одному пункту на строку",
                        verbose_name="Документы для приёма",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="programs/", verbose_name="Обложка"
                    ),
                ),
                (
                    "notice_date",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Объявление: дата"
                    ),
                ),
                (
                    "notice_text",
                    models.TextField(blank=True, verbose_name="Объявление: текст"),
                ),
                (
                    "notice_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Объявление: ссылка"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменена"),
                ),
            ],
            options={
                "verbose_name": "Программа",
                "verbose_name_plural": "Программы",
                "ordering": ["sphere__position", "position", "title"],
            },
        ),
        migrations.CreateModel(
            name="Sphere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Код")),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Направление",
                "verbose_name_plural": "Направления",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="ФИО"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="teachers/", verbose_name="Фото"
                    ),
                ),
                (
                    "page_url",
                    models.URLField(blank=True, verbose_name="Страница на hse.ru"),
                ),
            ],
            options={
                "verbose_name": "Преподаватель",
                "verbose_name_plural": "Преподаватели",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Название")),
                (
                    "hours",
                    models.CharField(blank=True, max_length=50, verbose_name="Часы"),
                ),
                (
                    "topics",
                    models.TextField(
                        blank=True,
                        help_text="По одной теме на строку",
                        verbose_name="Темы",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="catalog.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Модуль",
                "verbose_name_plural": "Программа обучения",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="FaqItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500, verbose_name="Вопрос")),
                ("answer", models.TextField(verbose_name="Ответ")),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faq",
                        to="catalog.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Частые вопросы",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="ProgramFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("plan", "Учебный план"), ("schedule", "Расписание")],
                        max_length=20,
                        verbose_name="Вид",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Название")),
                (
                    "size_label",
                    models.CharField(blank=True, max_length=50, verbose_name="Размер"),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Ссылка на hse.ru"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to="files/", verbose_name="Файл"
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="catalog.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы программы",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Отзыв")),
                (
                    "author",
                    models.CharField(blank=True, max_length=200, verbose_name="Автор"),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="program",
            name="sphere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="programs",
                to="catalog.sphere",
                verbose_name="Направление",
            ),
        ),
        migrations.CreateModel(
            name="ProgramTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about",
                    models.TextField(blank=True, verbose_name="Должность и регалии"),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_teachers",
                        to="catalog.program",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roles",
                        to="catalog.teacher",
                        verbose_name="Преподаватель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Преподаватель программы",
                "verbose_name_plural": "Преподаватели программы",
                "ordering": ["position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("program", "teacher"), name="unique_program_teacher"
                    )
                ],
            },
        ),
    ]
