# Generated by Django 5.2.17 on 2026-10-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_typeset_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="hidden_by_hand",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Скрыта вручную"
            ),
        ),
    ]
