# Generated by Django 5.2.17 on 2026-10-06 08:28

import django.core.validators
from django.db import migrations, models

from catalog.top_picks import pin_initial_top


def pin_existing(apps, schema_editor):
    pin_initial_top(apps.get_model("catalog", "Program").objects)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_sync_twice_a_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="top_position",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="От 1 до 12. Пусто — программа попадает в блок по ближайшему старту",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="Место в «Выборе слушателей»",
            ),
        ),
        migrations.RunPython(pin_existing, migrations.RunPython.noop),
    ]
