# Generated by Django 5.2.17 on 2026-10-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_program_top_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="hidden_on_landing",
            field=models.BooleanField(
                default=False,
                help_text="Преподаватель не попадёт в блок «Преподаватели» на главной странице. На страницах программ, в сравнении и в Telegram он остаётся. Обновление с hse.ru эту настройку не сбрасывает.",
                verbose_name="Не показывать на главной",
            ),
        ),
    ]
