# Generated by Django 5.2.17 on 2026-10-07 08:35

from django.db import migrations, models


def copy_hidden_to_shown(apps, schema_editor):
    apps.get_model("catalog", "Teacher").objects.filter(hidden_on_landing=True).update(show_on_landing=False)


def copy_shown_to_hidden(apps, schema_editor):
    apps.get_model("catalog", "Teacher").objects.filter(show_on_landing=False).update(hidden_on_landing=True)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_hide_teacher_on_landing"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="show_on_landing",
            field=models.BooleanField(
                default=True,
                help_text="Если выключить, преподаватель пропадёт из блока «Преподаватели» на главной странице. На страницах программ, в сравнении и в Telegram он остаётся. Обновление с hse.ru эту настройку не сбрасывает.",
                verbose_name="Показывать на главной",
            ),
        ),
        migrations.RunPython(copy_hidden_to_shown, copy_shown_to_hidden),
        migrations.RemoveField(
            model_name="teacher",
            name="hidden_on_landing",
        ),
        migrations.AlterField(
            model_name="program",
            name="locked",
            field=models.BooleanField(
                default=False,
                help_text="Программа не обновляется с hse.ru, ручные правки сохраняются",
                verbose_name="Правится вручную",
            ),
        ),
    ]
