# Generated by Django 5.2.17 on 2026-10-07 15:17

import django.core.validators
from django.db import migrations, models

from catalog.top_picks import pin_high_rating


def pin_programs(apps, schema_editor):
    pin_high_rating(apps.get_model("catalog", "Program").objects)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_teacher_show_on_landing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="top_position",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Программа попадает в блок «Программы с высоким рейтингом» и получает значок ★★★. Пусто — нет",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(7),
                ],
                verbose_name="Высокий рейтинг: место на главной (1–7)",
            ),
        ),
        migrations.RunPython(pin_programs, migrations.RunPython.noop),
    ]
