limit_req_zone $binary_remote_addr zone=admin_login:10m rate=10r/m;

server_tokens off;
resolver 127.0.0.11 valid=10s ipv6=off;

gzip on;
gzip_comp_level 5;
gzip_min_length 1024;
gzip_vary on;
gzip_types text/css application/javascript application/json image/svg+xml text/plain;

proxy_cache_path /var/cache/nginx/site levels=1:2 keys_zone=site:10m max_size=256m inactive=1d use_temp_path=off;
