# Generated by Django 5.2.17 on 2026-10-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(db_index=True, verbose_name="Время"),
                ),
                (
                    "session",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Сессия"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("pageview", "Просмотр страницы"),
                            ("heartbeat", "Время на странице"),
                            ("click", "Переход по сайту"),
                            ("outbound", "Переход на другой сайт"),
                            ("program", "Переход к программе"),
                            ("filter", "Фильтр каталога"),
                            ("scroll", "Прокрутка"),
                            ("exit", "Уход со страницы"),
                            ("form_error", "Ошибка отправки заявки"),
                        ],
                        max_length=16,
                        verbose_name="Тип",
                    ),
                ),
                ("path", models.CharField(max_length=300, verbose_name="Страница")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заголовок"
                    ),
                ),
                (
                    "referrer",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Источник"
                    ),
                ),
                (
                    "target",
                    models.CharField(blank=True, max_length=500, verbose_name="Цель"),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Подпись"
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(default=0, verbose_name="Время, мс"),
                ),
                (
                    "device",
                    models.CharField(
                        choices=[
                            ("mobile", "Телефон"),
                            ("tablet", "Планшет"),
                            ("desktop", "Компьютер"),
                        ],
                        max_length=8,
                        verbose_name="Устройство",
                    ),
                ),
                (
                    "language",
                    models.CharField(blank=True, max_length=16, verbose_name="Язык"),
                ),
                (
                    "scroll",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Прокрутка, %"
                    ),
                ),
            ],
            options={
                "verbose_name": "событие",
                "verbose_name_plural": "Посещаемость",
                "ordering": ["-occurred_at"],
            },
        ),
    ]
