# Generated by Django 5.2.17 on 2026-10-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_q", "0019_alter_task_options_alter_ormq_key_alter_ormq_lock_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannedTask",
            fields=[],
            options={
                "verbose_name": "задача по расписанию",
                "verbose_name_plural": "Расписание",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_q.schedule",),
        ),
        migrations.CreateModel(
            name="TaskRecord",
            fields=[],
            options={
                "verbose_name": "запись журнала задач",
                "verbose_name_plural": "Журнал задач",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_q.task",),
        ),
    ]
