# Generated by Django 5.2.17 on 2026-10-01 13:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0003_catalog_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Получена",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("program", "Заявка на программу"),
                            ("course-idea", "Идея курса"),
                            ("teaching", "Хочу стать преподавателем"),
                            ("feedback", "Отзыв о работе центра"),
                        ],
                        default="program",
                        max_length=20,
                        verbose_name="Тема",
                    ),
                ),
                (
                    "applicant_type",
                    models.CharField(
                        choices=[
                            ("personal", "За себя"),
                            ("corporate", "От организации"),
                        ],
                        default="personal",
                        max_length=20,
                        verbose_name="Кто подаёт",
                    ),
                ),
                (
                    "employees_count",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Сотрудников к обучению"
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Желаемые сроки"
                    ),
                ),
                ("first_name", models.CharField(max_length=80, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=80, verbose_name="Фамилия")),
                ("phone", models.CharField(max_length=40, verbose_name="Телефон")),
                ("email", models.EmailField(max_length=160, verbose_name="Почта")),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Должность"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Место работы"
                    ),
                ),
                (
                    "sources",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Откуда узнали"
                    ),
                ),
                (
                    "source_other",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Откуда узнали: другое"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="Комментарий"
                    ),
                ),
                (
                    "no_announcements",
                    models.BooleanField(default=False, verbose_name="Отказ от анонсов"),
                ),
                (
                    "program_title",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Название программы"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in-progress", "В работе"),
                            ("done", "Обработана"),
                            ("rejected", "Отклонена"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "mail_status",
                    models.CharField(
                        choices=[
                            ("queued", "Отправляется"),
                            ("sent", "Отправлено"),
                            ("failed", "Не отправлено"),
                            ("skipped", "Почта не настроена"),
                        ],
                        default="queued",
                        max_length=20,
                        verbose_name="Письмо",
                    ),
                ),
                (
                    "mail_error",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Ошибка письма"
                    ),
                ),
                (
                    "duplicate_key",
                    models.CharField(db_index=True, editable=False, max_length=300),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="catalog.program",
                        verbose_name="Программа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "ordering": ["-received_at"],
            },
        ),
    ]
