# Generated by Django 5.2.17 on 2026-10-02 10:21

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_purge_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=160, unique=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "topics",
                    models.JSONField(
                        default=applications.models.all_topics,
                        verbose_name="Темы заявок",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Получает письма"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Кто это"
                    ),
                ),
            ],
            options={
                "verbose_name": "получатель писем",
                "verbose_name_plural": "Получатели писем",
                "ordering": ["email"],
            },
        ),
        migrations.AddField(
            model_name="application",
            name="mail_attempts",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Попыток отправки"
            ),
        ),
    ]
