# Generated by Django 5.2.17 on 2026-10-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_applicant_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="applicant_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("personal", "Частное лицо"),
                    ("corporate", "Сотрудник организации"),
                ],
                default="personal",
                help_text="Только для заявки на программу",
                max_length=20,
                verbose_name="Кто будет обучаться",
            ),
        ),
    ]
