# Generated by Django 5.2.17 on 2026-10-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_applicant_type_only_for_programs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="position",
        ),
    ]
