# Generated by Django 5.2.17 on 2026-10-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_remove_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="source_other",
        ),
        migrations.RemoveField(
            model_name="application",
            name="sources",
        ),
    ]
