# Generated by Django 5.2.17 on 2026-10-07 10:17

from django.db import migrations, models

CORPORATE = "corporate"


def clear_personal_companies(apps, schema_editor):
    apps.get_model("applications", "Application").objects.exclude(applicant_type=CORPORATE).update(company="")



class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_remove_sources"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="company",
            field=models.CharField(
                blank=True,
                help_text="Только для корпоративной заявки",
                max_length=160,
                verbose_name="Организация-заказчик",
            ),
        ),
        migrations.RunPython(clear_personal_companies, migrations.RunPython.noop),
    ]
