# Generated by Django 5.2.17 on 2026-10-07 10:26

from django.db import migrations, models

ANONYMOUS_TOPICS = ("course-idea", "feedback")


def forget_contacts(apps, schema_editor):
    applications = apps.get_model("applications", "Application").objects.filter(topic__in=ANONYMOUS_TOPICS)
    applications.update(first_name="", last_name="", phone="", email="", no_announcements=False)



class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_company_only_for_corporate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="email",
            field=models.EmailField(blank=True, max_length=160, verbose_name="Почта"),
        ),
        migrations.AlterField(
            model_name="application",
            name="first_name",
            field=models.CharField(blank=True, max_length=80, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="application",
            name="last_name",
            field=models.CharField(blank=True, max_length=80, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="application",
            name="phone",
            field=models.CharField(blank=True, max_length=40, verbose_name="Телефон"),
        ),
        migrations.RunPython(forget_contacts, migrations.RunPython.noop),
    ]
