# Generated by Django 5.2.17 on 2026-10-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0009_anonymous_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="consent_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Согласие на обработку ПДн дано",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="consent_version",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=40,
                verbose_name="Версия текста согласия",
            ),
        ),
    ]
