# Generated by Django 5.2.17 on 2026-10-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0010_consent_record"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="no_announcements",
        ),
        migrations.AddField(
            model_name="application",
            name="ads_consent_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Согласие на рассылки дано",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="ads_consent_version",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=40,
                verbose_name="Версия текста согласия на рассылки",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="ads_consent_withdrawn_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Согласие на рассылки отозвано",
            ),
        ),
    ]
