# Generated by Django 5.2.17 on 2026-10-07 11:06

from django.db import migrations, models
from django.utils import timezone

CLOSED_STATUSES = ("done", "rejected")


def close_finished(apps, schema_editor):
    applications = apps.get_model("applications", "Application").objects.filter(status__in=CLOSED_STATUSES)
    applications.update(closed_at=timezone.now())



class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0011_ads_consent"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="closed_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Рассмотрена"
            ),
        ),
        migrations.RunPython(close_finished, migrations.RunPython.noop),
    ]
