# Generated by Django 5.2.17 on 2026-10-07 12:33

import applications.recipient_domain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0013_history_without_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailrecipient",
            name="email",
            field=models.EmailField(
                help_text="Только адрес @hse.ru: в письме все данные заявки.",
                max_length=160,
                unique=True,
                validators=[applications.recipient_domain.validate_recipient_domain],
                verbose_name="Адрес",
            ),
        ),
    ]
