# Generated by Django 5.2.17 on 2026-10-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("axes", "0010_accessattemptexpiration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lockout",
            fields=[],
            options={
                "verbose_name": "блокировка",
                "verbose_name_plural": "Блокировки",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("axes.accessattempt",),
        ),
        migrations.CreateModel(
            name="LoginJournal",
            fields=[],
            options={
                "verbose_name": "запись журнала входов",
                "verbose_name_plural": "Журнал входов",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("axes.accesslog",),
        ),
    ]
